// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udhkujfvexniizjujxym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkaGt1amZ2ZXhuaWl6anVqeHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzgxMjgsImV4cCI6MjA1NTA1NDEyOH0.IYP8YpzxS3gVFUYHUS9z1_XRSbAh94t2Lkq1-pkExZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);